### ISSUE TITLE
coef.msaenet() exclues intercept term

### ISSUE THREAD

**Issue by mwh3780** [nanxstats/msaenet#2]
I don't know if this is intended or not, but coef.msaenet() excludes the intercept term while coef.glmnet() does not.

```
library(msaenet)

dat = msaenet.sim.gaussian(
  n = 150, p = 20, rho = 0.6,
  coef = rep(1, 5), snr = 2, p.train = 0.7,
  seed = 1001)

msaenet.fit = msaenet(
  dat$x.tr, dat$y.tr,
  alphas = seq(0.2, 0.8, 0.2),
  nsteps = 3L, seed = 1003)

coef(msaenet.fit)     # coef.msaenet() exclues intercept
coef(msaenet.fit$model)     # coef.glmnet() returns intercept
```

**Comment by nanxstats** [comment]
Hi @michaelwhammer -- yes, we on purposely chose to show the coefficients of the variables while excluding the intercept. Three reasons:

1. Which variables are selected is what we want to focus on in this package. Therefore, the intercept is not entirely relevant anymore. Note that the `predict` method still uses the complete model with the possible intercept to make predictions -- the model didn't change at all, we only chose to show (a major) part of the results here.

2. The intercept itself is not that important as people usually thought, considering it is not being regularized at all in glmnet. In fact, the coefficients of the variables themselves are not important either. One [evidence](https://projecteuclid.org/euclid.bj/1363192037) is that you can refit a non-regularized linear model to get even better estimates of the coefficients after selection. For this case, the selection accuracy instead of the estimation bias becomes critical.

3. From the engineering perspective, we would rather not add too many lines of code to deal with the complexity created by the intercept, especially when [considering](https://github.com/road2stat/msaenet/blob/master/R/msaenet-tune-ncvreg.R#L272-L284) the nonconvex penalties from the ncvreg package together with glmnet. Including intercept here may also add extra complexity for the users to tell which variables are selected, but when intercepts are excluded, it'll be straightforward, e.g. with `msaenet.nzv`.

That being said, you can always use `msaenet.fit$model$a0` here to get the estimated intercept.
