### ISSUE TITLE
Possibility to provide user-supplied lambda sequence like glmnet

### ISSUE THREAD

**Issue by kevinegan31** [nanxstats/msaenet#6]
`glmnet` provides a `lambda` sequence option for the user to provide their own rather than allowing the algorithm to develop one. Is this a possible feature that could be added in? Or is it a limitation with the adaptive elastic-net?

Thanks.

**Comment by nanxstats** [comment]
Nice thought - I thought about this before, too!

It is technically easy to support this, while in practice I decided that it is better not to support this, because for me, the automatically generated lambda sequences often look sufficient and superior than the manually specified ones; also, lambda is a deeply involved parameter in the glmnet algorithms. To quote from the glmnet [vignette](https://cran.r-project.org/web/packages/glmnet/vignettes/glmnet.pdf):

> (Warning: Though such problems can be solved by glmnet, it is not recommended and is not the spirit of the package. glmnet fits the entire solution path for the lasso or elastic net problems efficiently with various techniques such as using warm starts and strong rules. Those advantages will disappear if the lambda sequence is forced to be only one value.)

> Alternatively, a more stable and strongly recommended way to perform this task is to first fit the entire lasso or elastic net path without specifying lambda, but then provide the requested lambda0 to a predict call to extract the corresponding coefficients.

Another minor design consideration is that is that it could complicate the interface. If we allow this, one might also need the flexibility to specify different sequences in different estimation steps.
